### ISSUE TITLE
Issue with ngx_pagespeed 1.10.33.4 and Safari

### ISSUE THREAD

**Issue by batmike** [kyl191/nginx-pagespeed#2]
First off, your repo on Fedora is great as it made the process of installing nginx with pagespeed so much easier. So thanks for keeping this updated!

I have been finding issues with redirects in Safari and submitted https://github.com/pagespeed/ngx_pagespeed/issues/1123 to which they (very quickly) replied that it had been fixed in the latest release just today. I pulled the nginx-pagespeed rpm and rebuilt it using both nginx 1.9.11 and pagespeed 1.10.33.5 and things are working great now with no strange URLs.

Not sure what all takes place when updated to either of those but I can confirm that simply updating the source packages was all I needed and everything built nicely and is working as expected.

**Comment by kyl191** [comment]
Thanks for letting me know! :) I was waiting for the new pagespeed release since I was running into errors building the rpms - I'll be rebuilding them tonight once I get home

**Comment by batmike** [comment]
Updates went great and no more strange duplicate http headers and redirects in Safari. Thanks!
